---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smarter-device-manager
  namespace: devices
spec:
  chart:
    spec:
      chart: smarter-device-manager
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 3.2.0
  interval: 5m0s
  values:
    conf:
    - devicematch: ^ttyUSB[0-9]*$
      nummaxdevices: 1
    - devicematch: ^video[0-9]*$
      nummaxdevices: 1
