---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dokuwiki
  namespace: organization
spec:
  chart:
    spec:
      chart: dokuwiki
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  interval: 5m0s
  values:
    dokuwikiUsername: alex
    existingSecret: dokuwiki-password
    service:
      type: ClusterIP
    persistence:
      existingClaim: dokuwiki-data
    ingress:
      enabled: true
      hostname: "wiki.${SECRET_DOMAIN}"
