ssh_authorized_keys:
- github:alexwaibel
write_files:
- path: /var/lib/connman/default.config
  content: |-
    [service_eth0]
    Type = ethernet
    IPv4 = 192.168.1.175/255.255.255.0/192.168.1.1
    Nameservers = 192.168.1.1
hostname: k3os
k3os:
  k3s_args:
  - server
  - "--etcd-expose-metrics true"
