---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duplicati-config
  namespace: backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
