---
- hosts:
    - localhost
  tasks:
    - name: Fetch service account for home-dns
      kubernetes.core.k8s:
        namespace: kube-system
        kind: ServiceAccount
        name: home-dns
      register: DNSServiceAccountRaw
      until: DNSServiceAccountRaw | json_query('result.secrets') is iterable
      retries: 5
      delay: 10

    - name: Fetch CA from service account secret
      kubernetes.core.k8s:
        namespace: kube-system
        kind: Secret
        name: "{{ DNSServiceAccountRaw | json_query('result.secrets[0].name') }}"
      register: DNSCertificateAuthorityRaw

    - name: Extract CA Cert from CA
      set_fact:
        DNSCertificateAuthority: '{{ DNSCertificateAuthorityRaw | json_query(''result.data."ca.crt"'') }}'

    - name: Extract CA Token from CA
      set_fact:
        DNSCertificateAuthorityToken: "{{ DNSCertificateAuthorityRaw | json_query('result.data.token') | b64decode }}"

    - name: Create kubeconfig
      copy:
        dest: "/tmp/kubeconfig-homedns"
        content: |
          ---
          apiVersion: v1
          kind: Config
          clusters:
          - name: home
            cluster:
              certificate-authority-data: {{ DNSCertificateAuthority }}
              server: https://{{ master_node_ip_address }}:6443
          contexts:
          - name: home
            context:
              cluster: home
              user: home-dns
          users:
          - name: home-dns
            user:
              token: {{ DNSCertificateAuthorityToken }}
          current-context: home
        mode: 0755

- name: Install coredns service
  import_playbook: coredns-service.yaml
