---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: networking
spec:
  chart:
    spec:
      chart: homer
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 3.2.1
  interval: 5m0s
  values:
    configmap.enabled: true
    envFrom:
      - configMapRef:
          name: config-map
    ingress:
      enabled: true
      hosts:
        - host: homepage.home.waibel.us
          paths:
            - path: /
              pathType: Prefix
