# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: slack-webhook
    namespace: observability
stringData:
    SECRET_ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:nPF5pmC9vcBb+oWMQqVSscNLvh7E4VV66+RWcBnP54yoZ1q/vdf8KBeWEfSAxOm9+8qBj+nx0gtQQONBrC/Dyv698qfWaWJebPat7R7602y0,iv:B9bzbVxqHcgCGxCD5RO6tizsn0+VoAKLDOg74PRZg60=,tag:oPDlBN3V68QZmjop56DpDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-20T07:58:10Z"
    mac: ENC[AES256_GCM,data:XiYoFD01r5uOQ2hgwCm/5vvIg2fyR5s61XWhxvpKajxKtqAhay8w9uZA5+lJIdVKGum1ayAPa85DdrcLE47LWDucyys7p+hERZEC60JWKVCL/CjMwqQwMn5VQ7P0m21305MPeaYqrlqovehwpFneOui+0m91KhNC0V7BC+fmOpA=,iv:ph9h+yC8TyG2v6y8nbrU4JUkh7sYj68dI+zPeSUWxao=,tag:E48ZRPfH/nsvLc+o8ITbyA==,type:str]
    pgp:
        - created_at: "2021-09-20T06:51:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7sq1npTE+1dARAApG5CM9A+JY6JceZKwUTOrR1cp0MyM6aD7nE5+LClnpda
            2QxojbQfyAzM+Cx1KRkcG+CCYG0ULPhxD+YkxqsirNU/XjFwUgjbOSLRiTo5N2/b
            Vw3YPwyPK3lyKEbiUsRrLngSRZ3FrPEiD/t2nm6Ynet9D3FWIOR4kPWSAyPMPGB8
            lauxri/FYCjvTx2ztJeM+gn6wIvXRlZRY2sm4DLm6AgzrN1QOBRPbbjz5hL/HYGm
            hCJaEl3WniZk5mTv3ovdV3QkWaMTFse/xChd7E+mcJaaPccfcHKZV+Ed3lVaTFDR
            76VZfPpIDRSFLz2peUCxWp1xsvXXzMMZLoz5a0z9xFoKtHqb0tGx6oW9OlTsvNlX
            lOR2h6AMu8Qd1fZYXRt1J4ahFIkgP289uYU/Ftg4TLZZ/cuMIMlIJ5iVUyqDDH0v
            0AG5ioEQGBpWSTRsrq4MozHWa+KwzI5o7hXullV4InyLPHueRclxNTc5/JEti1+6
            vk4GMTcW8Dcvke+9Y8MZFPVggeOihgODbKEXdla901dCCT0bqHTUKQmAPXh40vtG
            BpyKnOtQj6VhE/iUFaSVkl9IqNiMlslAUblIWy3ApjFvfFMTj8PxYH76tFF2C0iP
            SdCPdyAMnudbwGVedaQFgVN0zFT46MrQwK1WmJzUxPWR+a+3VE7likY2sPc+4W7S
            XgFRU4eMz77saojC3lO4y38pMUGKWDtYz7iTSiXJQYFTZkvlHZtWVcsx/DN3w5aE
            XUWSRubN+oOUNR3NtfNVwOpfLBEcajrzdbOTFf/uT8sWzDPs+96gMkDS2jJKYmw=
            =G0JU
            -----END PGP MESSAGE-----
          fp: 5BFE57B283EBFAA9C14392882895075AEB2D5149
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
