---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logitech-media-server-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
