---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 14.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m0s
  timeout: 20m0s
  values:
    alertmanager:
      config:
        route:
          routes:
          - match:
              alertname: Watchdog
            receiver: 'null'
          - match:
              alertname: KubeMemoryOvercommit
            receiver: 'null'
          - match:
              alertname: KubeCPUOvercommit
            receiver: 'null'
      ingress:
        enabled: true
        hosts:
        - "alert-manager.home.waibel.us"
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "nfs-client"
              resources:
                requests:
                  storage: 10Gi
    grafana:
      ingress:
        enabled: true
        hosts:
        - "grafana.home.waibel.us"
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    prometheus:
      ingress:
        enabled: true
        hosts:
        - "prometheus.home.waibel.us"
      prometheusSpec:
        retention: 14d
        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "nfs-client"
              resources:
                requests:
                  storage: 50Gi
