---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyperion-ng-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
