---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - devices
  - home
  - kube-system
  - media
  - networking
  - observability
  - organization
  - system-upgrade
