---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backups
  - devices
  - flux-system
  - home
  - kube-system
  - media
  - networking
  - observability
  - organization
