# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: basic-auth
    namespace: networking
stringData:
    users: ENC[AES256_GCM,data:TxLjoPO13YylxhgwzmAe+lFpGfYTQiv+Vhm2+jJVVyiVWiQEYOq3gXOppP4mjMjwO0RpYgbM4XoORIrWXjP4QfTNkUY=,iv:aqof5mKnpwzFHp1sEC9kib/Kegx2ovoBoBMIcmmSFD4=,tag:227VpGLSPNek0zCOWzCy2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-21T02:07:53Z"
    mac: ENC[AES256_GCM,data:+mR7C+GDf/IqcETNMa1+2X8wKLvyAeS3YgP5cczl8HkEUbIgFddN0AHL1fHyqBvWYOJNB9BAH84bBJYutHq3RWYOdipFz3a+ARmeERnwpQy4vCosOgtSl8qELKznf3qJdWn5A4hmHZHWM17SPVR/PAnXPJLmfKgVCUaOLcpj0r4=,iv:5Qcvlz2kgiRdcrYwdclHFfW5Iypu1Ka+6ZkdEjmnPEk=,tag:eCG0czyNDwLvZNhCY3vLXQ==,type:str]
    pgp:
        - created_at: "2021-09-21T01:54:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7sq1npTE+1dAQ//e/UeCcJv7HGH1tCPcfp+usJZGbXgC2OPdqHwgfL46BwQ
            aVHQZeC5jmc4tHHN/euovA0gdshgDusrAOxNJiSClat/7TxSU3tKw2xVkEfNS15V
            0TDeU/ynumK05Kwj0YtxF6kpSOOb0eblMyROmuTyS6JDTHCbFjv/YzA4fq3hND0W
            XgaQ0nTbRghEmo0hOX/wHSDu+/HSZgpsiKAyg+HFpx7T2f8t9289vDVJIhPuww+4
            zZzZCnNrxWP2YI64ImRe73r3uKAc27UlgDaA8r4yGNS7h0+cT2eZrGQss5mlx15Q
            q8xeBHKhYP7wA9nhe4ZUZD31y5P9I/wfRaP22VJA96K7kDU3lwsQw+TDOMhN4SV9
            /gPuqLk87K5wgQ/cutclBofU+aUAywj84IUfMhWZ0eDWCzg5kjAe3K366oCgPIM9
            Sw/EeV/tlu2EQkMvJCVim7y3MYSwcBs6KW3/MSLIjd4OsGoLGJdAn/aeeZTYwoxJ
            a8c89mWoxrF1Od37uDFJIkeSgA7czLKOVlrEEP87TXOdQOBYswilO8EjRc0x+mLp
            lC1kxhp3n09RKJDGxBqPTmgnWXTD5PE/lF8XCaJ0O1o9y2wbHek4YTLm+4ROSO9h
            bEa78bNq2M0258MpbkjHeEJPFS+mDAadYtlqNQeSa4S82eqxRUDAHm/4nkda0LXS
            XgGAzo6bHYdWjdwHF6U3SYpBDc34Mz4bB+0N62Fb7VxoEfm7fLA//OYh6pQShgKD
            RlCafCiNrWmEZLHrsp9SeWuV5lUWB+53/6pGXkEr8Q3t0xTi5CSHflNSCneGLg4=
            =Syse
            -----END PGP MESSAGE-----
          fp: 5BFE57B283EBFAA9C14392882895075AEB2D5149
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
