---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://repos.emqx.io/charts
      chart: emqx
      version: 4.3.8
      sourceRef:
        kind: HelmRepository
        name: emqx-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    service:
      type: LoadBalancer
      loadBalancerIP: ${SVC_EMQX_ADDR}
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_ADMIN_PASSWORD: "${SECRET_EMQX_ADMIN_PASSWORD}"
      EMQX_AUTH__USER__1__USERNAME: "${SECRET_MQTT_USERNAME}"
      EMQX_AUTH__USER__1__PASSWORD: "${SECRET_MQTT_PASSWORD}"
    emqxLoadedPlugins: >
      {emqx_auth_mnesia, true}.
      {emqx_bridge_mqtt, false}.
      {emqx_dashboard, true}.
      {emqx_management, true}.
      {emqx_recon, true}.
      {emqx_retainer, true}.
      {emqx_rule_engine, true}.
      {emqx_telemetry, false}.
    persistence:
      enabled: true
      size: 100Mi
      storageClass: "nfs-client"
      accessMode: ReadWriteOnce
