---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smarter-device-manager
  namespace: devices
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: smarter-device-manager
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    config:
      - devicematch: ^ttyUSB[0-9]*$
        nummaxdevices: 1
      - devicematch: ^video[0-9]*$
        nummaxdevices: 1
