---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dokuwiki
  namespace: organization
spec:
  chart:
    spec:
      chart: dev/helm
      sourceRef:
        kind: GitRepository
        name: bitnami
        namespace: flux-system
  interval: 5m0s
  values:
    ingress:
      enabled: true
      hosts:
        - host: wiki.home.waibel.us
          paths: ["/"]
    postgresql:
      persistence:
        existingClaim: dokuwiki-data
