---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki-data
  namespace: organization
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
