---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 6.3.1
  interval: 5m0s
  values:
    securityContext:
      privileged: true
    additionalVolumeMounts:
      - name: zwave-usb
        mountPath: /dev/ttyUSB0
      - name: zigbee-usb
        mountPath: /dev/ttyUSB1
    additionalVolumes:
      - name: zwave-usb
        hostPath:
          path: /dev/ttyUSB0
      - name: zigbee-usb
        hostPath:
          path: /dev/ttyUSB1
    ingress:
      enabled: true
      hosts:
        - host: hass.home.waibel.us
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - zwave-controller
    addons:
      codeserver:
        enabled: true
        workingDir: "/config"
        args:
          - --auth
          - "none"
        ingress:
          enabled: true
          hosts:
            - host: hass-config.home.waibel.us
              paths:
                - path: /
                  pathType: Prefix
        volumeMounts:
          - name: config
            mountPath: /config
