---
name: Schedule - Renovate Helm Releases

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */12 * * *'

jobs:
  renovate-helm-releases:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1

    - name: Renovate Helm Releases
      uses: k8s-at-home/renovate-helm-releases@v1
      with:
        cluster-path: "./cluster"

    - name: Create pull request for renovatebot helm-release annotations
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: renovate-annotations
        delete-branch: true
        title: "(deps) chore: update renovate annotations"
        signoff: true
        committer: "Alex Waibel <alexwaibel@users.noreply.github.com>"
        author: "Alex Waibel <alexwaibel@users.noreply.github.com>"
        assignees: "alexwaibel"
        commit-message: "(deps) chore: update renovate annotations"
        body: |
          Update HelmReleases using Renovate to pick up new Helm chart versions
        labels: renovate/annotations
