---
apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
resources:
  - cert-manager.yaml
  - devices.yaml
  - home.yaml
  - media.yaml
  - metallb-system.yaml
  - networking.yaml
  - observability.yaml
  - organization.yaml
